baseURL = 'https://yinyu8347.github.io/hugonews/'
languageCode = 'en-us'
title = '尹宇'
theme = 'ananke'
publishDir = "docs"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

canonifyurls = true
theme = 'ananke'
title = 'https://yinyu8347.github.io/hugonews/'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true